version: '3'
services:
  ksuite-middleware:
    build: .
    image: minidfx/ksuite-middleware:v0.4.0
    environment:
      - SECRET_KEY_BASE=<secret>
      - PHX_HOST=<host>
      - PORT=<port>
      - KDRIVE_ID=<id>
      - KSUITE_API_TOKEN=<token>
    ports:
      - 4000:4000
